### ISSUE TITLE
Repetitive Events work, BUT: The original date is always shown.

### ISSUE THREAD

**Issue by poljpocket** [ese-unibe-ch/ese2011-team3#103]
@lexruee and @poljpocket have implemented the repetitive events functionality.

It works like a charm, BUT it has one big bug:

The event - no matter what repetition - has always the original date. Example:

I create an event on 2011/10/01 which lasts one day and is repeating every week.
If I look at the event one week later (2011/10/08), it says it has 2011/10/01 as date on which it happens.

This shall be corrected. But how?

**Comment by poljpocket** [comment]
And two minutes later we have the solution! hahaha nice @lexruee

**Comment by poljpocket** [comment]
aaaaaaaaaand we threw the solution right away when we thought into it a bit more...

**Comment by lexruee** [comment]
and we solved it...
