### ISSUE TITLE
Presentation on Wednesday

### ISSUE THREAD

**Issue by Nick11** [ese-unibe-ch/ese2011-team3#104]
Who's taking care of that?

**Comment by wuschu** [comment]
i just finished a small presentation. it will cover the basic questions and gives a quick overview of what we have done so far and what problems we were dealing with. 
If you wanna see it, let me know. then i will send an email to all of you guys. 

Cheers,
Domi

**Comment by lexruee** [comment]
okay, send me a mail ;-) @wuschu
