### ISSUE TITLE
[registration] of new users

### ISSUE THREAD

**Issue by wuschu** [ese-unibe-ch/ese2011-team3#116]
remodel the homepage, so that you have the choice whether to login if you already have an account or to register if you are a new user. 
the registration has to have a CAPTCHA. (+0.5)

**Comment by lexruee** [comment]
some links:
http://osdir.com/ml/play-framework/2011-09/msg00125.html
http://groups.google.com/group/play-framework/browse_thread/thread/4ffa1fee1e6152b8/6f0201990219634b?lnk=gst&q=ov+secure#6f0201990219634b

**Comment by wuschu** [comment]
1291c3ab80a97ee6a18ce458a37701651e785fcf 
Validation has to be done. and if we want +0.5 pts we have to get the captcha done. 
captcha is already implemented in Main.. if you add a route to Main.captcha you get a new PINK!!!! captcha everytime you load the page. just the validation and integration issue again :)
