### ISSUE TITLE
[repeatable events] delete single instances

### ISSUE THREAD

**Issue by wuschu** [ese-unibe-ch/ese2011-team3#118]
in a series of repeatable events you have to be able to delete one event without deleting the whole list

**Comment by poljpocket** [comment]
we have to rethink the whole repetitive (actually, this is the right word for it because repeatable means 'wiederholbar' or 'reproduzierbar') events mechanism. I assume that we also enable editing specific events. One idea could be a new class 'RepetitiveEvent' which might be a subclass of 'Event'.

**Comment by lexruee** [comment]
@poljpockets the idea of a new subclass sounds reasonable, but it won't be an enitity, am I right?
