### ISSUE TITLE
[repeatable events] create additional types

### ISSUE THREAD

**Issue by wuschu** [ese-unibe-ch/ese2011-team3#119]
- repeating event on the last day of the month.
- on every 1st/2nd/3rd Mo/Tu/We... of every month
- every <XXX> weeks

**Comment by lexruee** [comment]
RepeatableType follows the strategy design pattern: http://en.wikipedia.org/wiki/Strategy_pattern
Context = Event
Strategy = RepeatableType with abstract method happensOnDay -> Interface
Enum types of RepeatableType: concrete implementations -> concrete strategy
