### ISSUE TITLE
[tests] running all tests results in UnexptectedException

### ISSUE THREAD

**Issue by lexruee** [ese-unibe-ch/ese2011-team3#122]
Because GlobalCalendar extends Calendar, the jpa tries to delete this "entity"  with a call of Fixtures.deleteAllModels(),
(my assumption).
This results in an UnexptectedException.

**Comment by poljpocket** [comment]
Right, I'd say that too...

Question then is, if annotations are being inherited!

**Comment by poljpocket** [comment]
The errors only occur in EventTest, CalendarTest
