### ISSUE TITLE
[repeatable events] dates aren't displayed correctly

### ISSUE THREAD

**Issue by wuschu** [ese-unibe-ch/ese2011-team3#123]
if you add an event that takes longer than one day, the date that is displayed is wrong. 
e.g.: 2011-12-13 12:00 - 2011-12-14 08:00 is displayed like: 2011-12-13 12:00 - 2011-12-13 08:00 one one day and as 2011-12-14 12:00 - 2011-12-14 08:00 on the other day.

**Comment by lexruee** [comment]
@wuschu jep, the class ViewHelper in the package utilities might be adapted for the repeatable events.
I can reproduce this bug only, if I choose the repeatable type daily...but such an event does not make any sense...

**Comment by poljpocket** [comment]
@lexruee @wuschu

Daily repetitive events as is makes no sense... -.- I assume we just delete that useless option.

But the problem remains! An event with longer that a week's duration shall not be repeated weekly, right?
