### ISSUE TITLE
Create a bootstrap

### ISSUE THREAD

**Issue by lexruee** [ese-unibe-ch/ese2011-team3#21]

**Comment by poljpocket** [comment]
PLEASE FOR GOD'S SAKE MAKE A .YML!!!

**Comment by poljpocket** [comment]
Please add events too... Maybe we'll need another constructor for Event to accept date STRINGs formatted in a specific way. I don't see how to create Date objects directly in YAML.

**Comment by lexruee** [comment]
yes, i've planned that too, don't be impatient ;-)
