### ISSUE TITLE
Error: play wants to load module secure out off workspace

### ISSUE THREAD

**Issue by lexruee** [ese-unibe-ch/ese2011-team3#22]
the terminal says:
...
23:52:38,671 ERROR ~ Module secure will not be loaded because D:\play\modules\secure does not exist
...

I don't have such an path in my workspace.

**Comment by lexruee** [comment]
play wants always to load "D:\play\modules\secure" but this folder does not exist in my workspace, I already deleted all tmp files and eclipsified the project...

**Comment by poljpocket** [comment]
Just delete this folder in the project tree. This comes from the problems @wuschu had on windows.

FYI: This is just a warning, the app runs anyway

**Comment by poljpocket** [comment]
@lexruee just update to HEAD and eclipsify your project. The import is gone now...
