### ISSUE TITLE
Tooltip for Event form

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2011-team3#44]
It's confusing if you don't get a clearly visible hint as to what the correct form of a date/time declaration is in the form to create events. I think there is something like a placeholder in HTML (the search box in github does it at least... couldn't you reverse-engineer that?)

**Comment by zombiecalypse** [comment]
Obvioulsy, if you could do that, that would solve the whole thing. Could you
do that?
On Oct 16, 2011 12:36 PM, "Alex" <
reply@reply.github.com>
wrote:

**Comment by lexruee** [comment]
Theoretically yes, but actually I don't want to.

I prefer the html placeholder solution...the date picker feature could be realised in a further iteration phase.

I suggest to focus on our primary issues.

**Comment by poljpocket** [comment]
@lexruee implementing this isn't a big deal actually...

**Comment by lexruee** [comment]
well, then you know, what you have to do @poljpocket
