### ISSUE TITLE
When you change the model, adapt the tests please!

### ISSUE THREAD

**Issue by poljpocket** [ese-unibe-ch/ese2011-team3#49]
@lexruee, your changes to the model made the EventTest fail. Please correct this because I cannot tell what's going wrong. Thanks.

**Comment by lexruee** [comment]
@poljpocket hm...sry, but i've no erros, when i run all the tests!

**Comment by lexruee** [comment]
i ran the test on my ubuntu system too,...but i have no tests that fail....

**Comment by poljpocket** [comment]
all ok, I wasn't on the newest commit and merged something I thought is finished. But it wasn't. My fault
