### ISSUE TITLE
can a user follow his own events?

### ISSUE THREAD

**Issue by Nick11** [ese-unibe-ch/ese2011-team3#75]
Can I follow an event from my calendar A in my calendar B?

**Comment by poljpocket** [comment]
very good question... I'd say no! That simply doesn't make any sense if you should be able to, right?

**Comment by Nick11** [comment]
well, he could have two calendars, a private one and a public one and an event, that fits in both contexts. (like a dinner with his business partners). but lets ask the customer about that and leave it for the moment.

**Comment by poljpocket** [comment]
either way this isn't a big deal...
