### ISSUE TITLE
many-to-many implentation between calendar / event

### ISSUE THREAD

**Issue by lexruee** [ese-unibe-ch/ese2011-team3#76]
i soved this probelm, but i didn't used the many-to-many annotation tag. the same thing can also be done by a new object called CalendarEventRelation. 

See branch exp_event_alt, there is the alternative implementation (tests!) of this many-to-many relationship.
the cool thing is, that all tests are green!

**Comment by Nick11** [comment]
I can't figure out how this should work. It seems like there are no such CalendarEventRelations in the events and calendars lists. If you can get it working, great. I can't.

**Comment by lexruee** [comment]
at the moment we have two implementation:
branch exp_event uses a new object called CalendarEventRelation.

branch exp_event_manytomany uses the jpa many-to-many annotation....

the question is which implementation should we use?

i just updated the exp_event branch and exp_event_manytomany, look at the tests how its works....

**Comment by lexruee** [comment]
we use the many-to-many annotation solution...
