### ISSUE TITLE
Request: Add property defaultCalendar to User model

### ISSUE THREAD

**Issue by poljpocket** [ese-unibe-ch/ese2011-team3#77]
We plan to display a calendar directly on the home page, just after an user has logged in. Every user gets the possibility to set it's default calendar in the profile settings. To achieve this, we need to save this somewhere. So, I assume, you just make a new property in the User model, which is called 'defaultCalendar'.

This produces several problems:
- The defaultCalendar may not be null unless there's no calendars for the user.
- The defaultCalendar must be one of the user's own calendars. This raises a little synchronization problem.

With some assertions or exception raisings, you should abandon these easily.

Thanks @lexruee, @Nick11, @tschwander

**Comment by poljpocket** [comment]
Could you finish this by today evening? You can format a patch just containing this file. Send it to me and I can apply it to my branch.

Thanks, Julian

**Comment by Nick11** [comment]
I couldn't finish it by now. I still have some problem setting the defaultCalendar as the first calendar created by the bootstrap or any calendar not added with the addCalendar() method in the User model.
Probably need some help with this.
