### ISSUE TITLE
reorganize branches / exp_event should be up to date

### ISSUE THREAD

**Issue by Nick11** [ese-unibe-ch/ese2011-team3#81]
afaik we're were only working on the exp_event_manytomany these days. but we should keep the exp_event up to date.
@alex could you do that? maybe you should just switch the name of these branches. on the exp_event we currently have the alternative version of the many-to-many relation, that we probably won't need anymore. so you could move that to som exp_event_relationObject branch, or so.

**Comment by lexruee** [comment]
Our working branch is now exp_event, this branch is based on the branch exp_event_manytomany.
The other branch exp_event_relationobject is the alternative implementation.
