### ISSUE TITLE
JavaDoc in User model

### ISSUE THREAD

**Issue by poljpocket** [ese-unibe-ch/ese2011-team3#90]

**Comment by wuschu** [comment]
i it is not how it was supposed to be, reopen the issue and let me know.

**Comment by poljpocket** [comment]
Have a look at your commit. There's an inline note.

**Comment by wuschu** [comment]
i adapted some things. i don't exactly know if the links i made work, but i tried. let me know if that's better. 

n.b: i really don't know why the commit message is the merge branch thing...

**Comment by poljpocket** [comment]
Yes, perfect!
