### ISSUE TITLE
list of the vocabulary used in the code. (put on ESE wiki)

### ISSUE THREAD

**Issue by wuschu** [ese-unibe-ch/ese2011-team3#99]
List your vocabulary in a page documentation/vocabulary. The vocabulary follows the rule "One word for one concept". The chosen word should be used consistenty in the project. For instance, user, contact, friend, participant, follower, might all be synonyms for one single concept—or maybe not. Use words consistently. The vocabulary you list here might grow later. It is an asset for you to name elements in your project. 

-- as seen on ESE homepage

**Comment by Nick11** [comment]
I've add the following terms:
- User, person using the application, owning, editing and viewing the calendars.
- Contact,  ''is a ''user who has access to your public calendars.
- Follower, ''is a ''user following an other users event.
- Owner,    ''is the'' user owning a specific calendar or event.
- Profile,  summery that displays some information of a users.
- Calendar, calendar/agenda containing events
- Event,    element of a calendar, representing an entry in it.
- Note, remark concerning a specific event.
- Date, date and time describing beginning or end of an event.

Am I missing something?

**Comment by wuschu** [comment]
maybe in Event add: can be public or private, if public can be followed. can be repeatable? 
otherwise from my POV it looks neat.
